version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_USER=devops_user
      - MYSQL_PASSWORD=secret_pass
      - MYSQL_DATABASE=company_db
      - MONGO_URL=mongodb://mongo_db:27017/logs_db
    depends_on:
      - mysql_db
      - mongo_db
  mysql_db:
    image: mysql:8.0
    container_name: enterpraise-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: company_db
      MYSQL_USER: devops_user
      MYSQL_PASSWORD: secret_pass
    volumes:
      - mysql_data:/var/lib/mysql
  mongo_db:
    image: mongo:latest
    container_name: enterprise-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
      
volumes:
  mysql_data:
  mongo_data: